# Generated by Django 2.1.2 on 2018-10-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tarefas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tarefa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='projetos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Projeto'),
            preserve_default=False,
        ),
    ]
