# Generated by Django 2.1.2 on 2018-11-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='conteudo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='deslike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pergunta'),
        ),
    ]
