# Generated by Django 2.1.2 on 2018-11-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181110_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
    ]
