# Generated by Django 2.1.2 on 2018-10-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181019_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='projetos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Projeto'),
        ),
    ]
