# Generated by Django 2.1.1 on 2018-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Criação'),
        ),
    ]
