# Generated by Django 2.1.2 on 2018-10-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tarefa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Projeto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
    ]
