# Generated by Django 2.1.2 on 2018-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_projeto_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(default=True, max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_vencimento',
            field=models.DateField(null=True, verbose_name='Concluir até:'),
        ),
    ]
