# Generated by Django 2.1.2 on 2018-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181024_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
