# Generated by Django 2.1.2 on 2018-10-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projeto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='detalhes',
            field=models.CharField(default='', max_length=200, verbose_name='Detalhes'),
        ),
    ]
