# Generated by Django 2.1.2 on 2018-10-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181024_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='app/img/uploads/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
    ]
