# Generated by Django 2.1.2 on 2018-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181024_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='app/imgs/uploads/'),
        ),
    ]
