# Generated by Django 2.1.1 on 2018-11-06 13:54

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181024_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nomeCompleto',
            field=models.CharField(default='', max_length=50, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Projeto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=app.models.uploac_location, verbose_name='Foto do perfil'),
        ),
    ]
