# Generated by Django 2.1.1 on 2018-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181106_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nomeCompleto',
            field=models.CharField(default=True, max_length=50, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(default=True, max_length=50, verbose_name='Usuario'),
        ),
    ]
