# Generated by Django 2.1.1 on 2018-11-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181106_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeCompleto',
            field=models.CharField(max_length=50, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
