# Generated by Django 2.1.1 on 2018-11-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20181106_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
